# These are supported funding model platforms

github: [ajhalili2006]
patreon: ajhalili2006
open_collective: # Replace with a single Open Collective username
ko_fi: ajhalili2006
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ajhalili2006
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ["https://paypal.me/ajhalili2006","https://getalby.com/p/ajhalili2006"]
